export default {
  Beverages: {
    Tea: 25,
    "Masala Tea": 25,
    "Tea With Cookies": 30,
    "Green Tea": 25,
    "Lemon Tea": 25,
    "Black Tea": 25,
    Coffee: 30,
    "Coffee with Cookies": 40,
    "Black Coffee": 25,
    "Cold Coffee": 60,
    "Cold Coffee with Ice-Cream": 80,
    "Lemon Water/ Soda": 30,
    "Hot Milk": 40,
    "Milk Shake (Vanilla/Strawberry/Chocolate)": "80/85/85",
    "Butter Milk": 25,
    "Lassi Sweet & Salted": 50,
    "Canned Juice (Pineapple/Mango/Mix Fruits)": 70,
    "Fresh Fruit Juice (Watermelon/Pineapple/Mix Fruits)": 60,
  },
  "Breads & Sandwiches": {
    "White Butter Toast": 25,
    "Multi Grain Toast": 35,
    "Plain Veg Sandwich": 100,
    "Grilled Veg Sandwich": 110,
    "Veg Cheese Sandwich (Plain/ Grilled)": "130/150",
    "Chicken Sandwich (Plain/Grilled)": "160/180",
  },
  "Special Days": {
    "Poori Bhaji": 70,
    "Chole Bhature": 80,
    "Pav Bhaji": 80,
    "Paratha Aloo Pyaz/Gobhi/Paneer/With": "80/100/100",
    "Curd & Pickle": 25,
    Samosa: 75,
    "Veg Cutlet": 65,
    "Bombay Vada Pav": 80,
  },
  "South Indian (on weekends)": {
    "Idli /Vada/ Uttapam With Sambhar & Chutney": 80,
    "Plain/Masala/Paneer/ Cheese Dosa With Sambhar & Chutney": "80/90/100/120",
  },
  "Egg Dishes": {
    "Plain Omelette With Bread Toast": 60,
    "Masala Omelette Bread Toast": 70,
    "Cheese Omelette With Bread Toast": 80,
    "Boiled Egg (1 pc )": 20,
    "Omelette With Multi Grain Toast": 80,
    "Scrambled Egg Bread Toast": 75,
  },
  "Papad/Chaat": {
    "Chana Chaat": 40,
    "French Fry": 50,
    "Sprout Moong Chaat": 50,
    "Rosted Papad ( 2 pc )": 20,
    "Masala Papad": 25,
    "Papad Bhurji": 65,
    "Butter Papad": 25,
    "Peanut Masala": 60,
    "Mirchi Fry": 30,
    "Palak Patta Chaat": 140,
  },
  "Snacks (Non-Veg)": {
    "Murg Malai Tikka": 240,
    "Chicken Tikka": 230,
    "Lehsuni Chicken Tikka": 240,
    "Kachmoli Chicken Tikka": 250,
    "Chicken Seekh Kebab": 210,
    "Grilled Chicken (With Chicken Mushroom Sauce)": 350,
    "Fish Tikka": 230,
    "Fish Finger": 240,
    "Achari Fish Tikka": 230,
    "Grilled Fish (With Lemon Butter Sauce)": 400,
    "Tandoori Chicken (Full/Half)": "500/350",
    "Mutton Shami Kebab": 240,
    "Mutton Seekh Kebab": 240,
    "Chicken Lollipop": 240,
    "Chilly Chicken": 220,
    "Non-Veg Platter": 260,
    "Chicken Pesto": 299,
    "Chicken Panang": 299,
    "Chicken Tikka Pizza": 250,
  },
  "Snacks (Veg)": {
    "Sauté Vegetable": 150,
    "Sauté Mushroom": 200,
    "Sauté broccoli": 200,
    "Sauté paneer": 200,
    "Dahi Kebab": 100,
    "Hara Bhara Kebab": 100,
    "Veg Pakora": 70,
    "Kachumber Pakora": 120,
    "Paneer Pakora": 120,
    "Paneer Tikka": 160,
    "Awadhi Paneer Tikka": 250,
    "Tandoori Mushroom": 160,
    "Tandoori Aloo": 100,
    "Tandoori Broccoli (Seasonal)": 150,
    "Dawat Soya Chaap": 160,
    "Afgani Soya Chaap": 160,
    "Cheese Jalapeno Burasi Kebab": 199,
    "Vegetable Seekh Kebab": 100,
    "Thar Ke Kebab (Papad Roll)": 150,
    "Crispy Kurkure Mushroom": 140,
    "Kurkure Paneer": 185,
    "Kalmi Vada": 200,
    "Vegetable Cheese Cilantro": 200,
    "Palak Patta Chat": 200,
    "Paneer Spinach Roll": 299,
    "Grilled Paneer (Tomato Concasse Sauce)": 299,
  },
  Chinese: {
    "Chilly Paneer": 150,
    "Honey Chilly Potato": 100,
    "Crispy Corn": 120,
    "Spring Roll": 80,
    "Crispy Vegetable": 100,
    "Veg Chowmin": 110,
    "Veg Hakka Noodle (Chilly/Garlic)": 100,
    "Veg Manchurian (Dry/Gravy)": 110,
    "Veg Fried Rice": 110,
    "Butter Garlic Chilly Water Chestnut": 199,
    "Chilly Mushroom": 120,
    "Baby Corn Salt & Paper": 180,
    "Wok Tok Chilly Fish": 250,
  },
  Italian: {
    "Veg Surprise Pizza": 290,
    "Margherita Pizza": 290,
    "Pizza Salad": 299,
    "Paneer Tikka Pizza": 290,
    "Garlic Bread": 85,
    "Cheese Chilly Toast": 85,
    "Choice Of Pasta (Red/Pink/White)": 285,
    "Panang Vegetables": 299,
  },
  "Salad & Raita": {
    "Veg. Raita": 75,
    "Boondi Raita": 65,
    "Pineapple Raita": 80,
    "Plain Curd": 45,
    "Green Salad": 20,
    "Laccha Pyaz": 30,
    "Onion Salad": 80,
    "Caesar Salad": 80,
  },
  "Veg Soups": {
    "Tomato Soup": 60,
    "Veg Hot & Sour Soup": 75,
    "Veg Manchow Soup": 75,
    "Veg Sweet Corn Soup": 75,
    "Veg Clear Soup": 75,
  },
  "Non-Veg Soups": {
    "Chicken Hot & Sour Soup": 100,
    "Chicken Mushroom Soup": 100,
    "Chicken Sweet Corn Soup": 100,
    "Chicken Clear Soup": 100,
  },
  Breads: {
    "Butter Naan": 50,
    "Garlic Naan": 60,
    "Plain Naan": 40,
    "Onion Naan": 40,
    "Lachha Parantha": 40,
    "Pudhina Parantha": 55,
    "Missi Roti": 25,
    "Stuff Naan": 65,
    "Paneer Parantha": 50,
    "Stuff Parantha": 60,
    "Tandoori Roti (Plain)": 15,
    "Tandoori Roti (With Butter)": 20,
    "Khamiri Roti": 30,
    "Tawa Roti Plain": 10,
    "Tawa Roti (With Butter)": 15,
    "Jangli Naan": 65,
  },
  Rice: {
    "Steamed Rice": 60,
    "Jeera Rice": 80,
    "Veg.Pulao": 120,
    "Veg.Biryani": 150,
    "Fried Rice": 110,
    "Khichdi (Plain/Masala/Vegetable)": "100/110/120",
  },
  "Veg Combo Meal": {
    "Paneer Combo (Salad, Raita, Paneer, Rice, 2 Breads, & Sweet)": 200,
    "Veg. Combo (Salad, Raita, Rice, 2 Breads, & Sweet)": 180,
    "Dal Combo (Salad, Raita, Dal, Rice, 2 Breads, & Sweet)": 180,
    "Sarso Ka Saag Combo (Seasonal)": 199,
    "Veg Combo Meal": 200,
  },

  "Non-Veg Combo Meal": {
    "Mutton Combo (Salad, Raita, Mutton, Rice, 2 Breads, & Sweet)": 290,
    "Chicken Combo (Salad, Raita, Chicken, Rice, 2 Breads, & Sweet)": 250,
    "Egg Combo ( Salad, Raita, Egg, Rice 2 Breads, & Sweet)": 220,
  },
  "Main Course (Veg)": {
    "Paneer Rajwadi": 230,
    "Paneer Khada Masala": 170,
    "Chatpata Paneer": 230,
    "Paneer Butter Masala": 230,
    "Paneer Lababdar": 230,
    "Palak Paneer": 200,
    "Kadhai Paneer": 200,
    "Shahi Paneer": 200,
    "Paneer Bhurji": 120,
    "Malai Kofta": 180,
    "Methi Malai Matter": 160,
    "Methi Malai Corn": 160,
    "Veg. Diwani Handi": 150,
    "Mix Vegetable": 130,
    "Corn Palak": 150,
    "Palak Tamatar": 100,
    "Pindi Chana": 160,
    "Gatta Masala": 130,
    "Dum Aloo": 115,
    "Aloo Pyaz": 140,
    "Seasonal Vegetable (Home style)": 150,
  },
  "Main Course (Non-Veg)": {
    "Jeera Aloo": 100,
    "Dal Tadka": 120,
    "Dal Dabha": 150,
    "Dal Rambagh": 185,
    "Dal With Butter": 140,
    "Chana Masala": 160,
    "Bhuna Gosht": 400,
    "Lal Mass": 420,
    "Mutton Rogan Josh": 420,
    "Mutton Curry ( Home Style)": 420,
    "Butter Chicken Full/Half": "420/250",
    "Chicken Tikka Masala": 420,
    "Chicken Curry Half/ Full": "475/290",
    "Egg Curry (2 Pc Mutton Gravy)": 200,
    "Egg Curry (2 Pcs)": 165,
    "Mutton Biryani (2 Pc)": 320,
    "Chicken Biryani (2 Pc)": 200,
    "Chicken Fried Rice": 160,
    "Fish Curry (4 Pc)": 350,
  },
  Desserts: {
    "Mishri Mawa": 70,
    "Moong Dal Halwa (Seasonal)": 70,
    "Gajar Ka Halwa (Seasonal)": 70,
    "Gulab Jamun (2 Pc)": 60,
    "Matka Kulfi": 70,
    "Flavoured Kulfi": 65,
    "Vanilla Icecream": 35,
    "Strawberry Icecream": 35,
    "Chocolate Icecream": 50,
    "Mango Icecream": 50,
    "Butterscotch Icecream": 50,
    "American Nuts Icecream": 60,
  },
  "Beverages & Snacks": {
    Cappuccino: 85,
    "Café Latte": 85,
    Espresso: 85,
    Americano: 85,
    "Café Frappe": 100,
    "Chocolate Shake": 80,
    "Strawberry Shake": 100,
    "Ice Tea (Lemon)": 80,
  },
};
